// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/environment/environment_enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment {

  /// <summary>Holder for reflection information generated from morai/environment/environment_enum.proto</summary>
  public static partial class EnvironmentEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/environment/environment_enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnvironmentEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cihtb3JhaS9lbnZpcm9ubWVudC9lbnZpcm9ubWVudF9lbnVtLnByb3RvEhlt",
            "b3JhaV9zaW1fYXBpLmVudmlyb25tZW50Kp4BCgtXZWF0aGVyVHlwZRIWChJX",
            "RUFUSEVSX1RZUEVfU1VOTlkQABIXChNXRUFUSEVSX1RZUEVfQ0xPVURZEAES",
            "FgoSV0VBVEhFUl9UWVBFX0ZPR0dZEAISFgoSV0VBVEhFUl9UWVBFX1NUT1JN",
            "EAMSFgoSV0VBVEhFUl9UWVBFX1JBSU5ZEAQSFgoSV0VBVEhFUl9UWVBFX1NO",
            "T1dZEAUqagoKU2Vhc29uVHlwZRIWChJTRUFTT05fVFlQRV9XSU5URVIQABIW",
            "ChJTRUFTT05fVFlQRV9TUFJJTkcQARIWChJTRUFTT05fVFlQRV9TVU1NRVIQ",
            "AhIUChBTRUFTT05fVFlQRV9GQUxMEAMqMwoRRW52VmlzaWJpbGl0eVR5cGUS",
            "HgoaRU5WX1ZJU0lCSUxJVFlfVFlQRV9QVURETEUQAEIySAGqAi1Db3JlTGli",
            "LkdycGMuUHJvdG9idWYuTW9yYWlTaW1BUEkuRW52aXJvbm1lbnRiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment.WeatherType), typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment.SeasonType), typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Environment.EnvVisibilityType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum WeatherType {
    [pbr::OriginalName("WEATHER_TYPE_SUNNY")] Sunny = 0,
    [pbr::OriginalName("WEATHER_TYPE_CLOUDY")] Cloudy = 1,
    [pbr::OriginalName("WEATHER_TYPE_FOGGY")] Foggy = 2,
    [pbr::OriginalName("WEATHER_TYPE_STORM")] Storm = 3,
    [pbr::OriginalName("WEATHER_TYPE_RAINY")] Rainy = 4,
    [pbr::OriginalName("WEATHER_TYPE_SNOWY")] Snowy = 5,
  }

  public enum SeasonType {
    [pbr::OriginalName("SEASON_TYPE_WINTER")] Winter = 0,
    [pbr::OriginalName("SEASON_TYPE_SPRING")] Spring = 1,
    [pbr::OriginalName("SEASON_TYPE_SUMMER")] Summer = 2,
    [pbr::OriginalName("SEASON_TYPE_FALL")] Fall = 3,
  }

  public enum EnvVisibilityType {
    [pbr::OriginalName("ENV_VISIBILITY_TYPE_PUDDLE")] Puddle = 0,
  }

  #endregion

}

#endregion Designer generated code
