// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/infrastructure/infrastructure.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure {

  /// <summary>Holder for reflection information generated from morai/infrastructure/infrastructure.proto</summary>
  public static partial class InfrastructureReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/infrastructure/infrastructure.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InfrastructureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ciltb3JhaS9pbmZyYXN0cnVjdHVyZS9pbmZyYXN0cnVjdHVyZS5wcm90bxIc",
            "bW9yYWlfc2ltX2FwaS5pbmZyYXN0cnVjdHVyZRoZbW9yYWkvY29tbW9uL3Jl",
            "c3VsdC5wcm90bxokbW9yYWkvY29tbW9uL29iamVjdF9pZGVudGlmaWVyLnBy",
            "b3RvGihtb3JhaS9pbmZyYXN0cnVjdHVyZS90cmFmZmljX2xpZ2h0LnByb3Rv",
            "Gidtb3JhaS9pbmZyYXN0cnVjdHVyZS9pbnRlcnNlY3Rpb24ucHJvdG8ypQQK",
            "DkluZnJhc3RydWN0dXJlEn0KE0dldFRyYWZmaWNMaWdodEluZm8SNi5tb3Jh",
            "aV9zaW1fYXBpLmluZnJhc3RydWN0dXJlLkdldFRyYWZmaWNMaWdodEluZm9Q",
            "YXJhbRouLm1vcmFpX3NpbV9hcGkuaW5mcmFzdHJ1Y3R1cmUuVHJhZmZpY0xp",
            "Z2h0SW5mbxJjChRTZXRUcmFmZmljTGlnaHRTdGF0ZRI0Lm1vcmFpX3NpbV9h",
            "cGkuaW5mcmFzdHJ1Y3R1cmUuVHJhZmZpY0xpZ2h0U3RhdGVQYXJhbRoVLm1v",
            "cmFpX3NpbV9hcGkuUmVzdWx0EmkKFUdldEludGVyc2VjdGlvblRMSW5mbxIf",
            "Lm1vcmFpX3NpbV9hcGkuT2JqZWN0SWRlbnRpZmllchovLm1vcmFpX3NpbV9h",
            "cGkuaW5mcmFzdHJ1Y3R1cmUuSW50ZXJzZWN0aW9uU3RhdGUSXgoUU2V0SW50",
            "ZXJzZWN0aW9uUGhhc2USLy5tb3JhaV9zaW1fYXBpLmluZnJhc3RydWN0dXJl",
            "LkludGVyc2VjdGlvblBoYXNlGhUubW9yYWlfc2ltX2FwaS5SZXN1bHQSZAoX",
            "U2V0SW50ZXJzZWN0aW9uU2NoZWR1bGUSMi5tb3JhaV9zaW1fYXBpLmluZnJh",
            "c3RydWN0dXJlLkludGVyc2VjdGlvblNjaGVkdWxlGhUubW9yYWlfc2ltX2Fw",
            "aS5SZXN1bHRCNUgBqgIwQ29yZUxpYi5HcnBjLlByb3RvYnVmLk1vcmFpU2lt",
            "QVBJLkluZnJhc3RydWN0dXJlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ResultReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifierReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
