// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/infrastructure/intersection.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure {

  /// <summary>Holder for reflection information generated from morai/infrastructure/intersection.proto</summary>
  public static partial class IntersectionReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/infrastructure/intersection.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IntersectionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cidtb3JhaS9pbmZyYXN0cnVjdHVyZS9pbnRlcnNlY3Rpb24ucHJvdG8SHG1v",
            "cmFpX3NpbV9hcGkuaW5mcmFzdHJ1Y3R1cmUaJG1vcmFpL2NvbW1vbi9vYmpl",
            "Y3RfaWRlbnRpZmllci5wcm90bxoobW9yYWkvaW5mcmFzdHJ1Y3R1cmUvdHJh",
            "ZmZpY19saWdodC5wcm90byJPChFJbnRlcnNlY3Rpb25QaGFzZRIrCgJpZBgB",
            "IAEoCzIfLm1vcmFpX3NpbV9hcGkuT2JqZWN0SWRlbnRpZmllchINCgVwaGFz",
            "ZRgCIAEoBSKuAgoUSW50ZXJzZWN0aW9uU2NoZWR1bGUSKwoCaWQYASABKAsy",
            "Hy5tb3JhaV9zaW1fYXBpLk9iamVjdElkZW50aWZpZXISSwoHdmVoaWNsZRgC",
            "IAMoCzI6Lm1vcmFpX3NpbV9hcGkuaW5mcmFzdHJ1Y3R1cmUuVHJhZmZpY0xp",
            "Z2h0U2NoZWR1bGUuVmVoaWNsZRJJCgZ5ZWxsb3cYAyADKAsyOS5tb3JhaV9z",
            "aW1fYXBpLmluZnJhc3RydWN0dXJlLlRyYWZmaWNMaWdodFNjaGVkdWxlLlll",
            "bGxvdxJRCgpwZWRlc3RyaWFuGAQgAygLMj0ubW9yYWlfc2ltX2FwaS5pbmZy",
            "YXN0cnVjdHVyZS5UcmFmZmljTGlnaHRTY2hlZHVsZS5QZWRlc3RyaWFuImoK",
            "EUludGVyc2VjdGlvblN0YXRlEkYKDnRyYWZmaWNfbGlnaHRzGAEgAygLMi4u",
            "bW9yYWlfc2ltX2FwaS5pbmZyYXN0cnVjdHVyZS5UcmFmZmljTGlnaHRJbmZv",
            "Eg0KBXBoYXNlGAIgASgFQjVIAaoCMENvcmVMaWIuR3JwYy5Qcm90b2J1Zi5N",
            "b3JhaVNpbUFQSS5JbmZyYXN0cnVjdHVyZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifierReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionPhase), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionPhase.Parser, new[]{ "Id", "Phase" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionSchedule), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionSchedule.Parser, new[]{ "Id", "Vehicle", "Yellow", "Pedestrian" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionState), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionState.Parser, new[]{ "TrafficLights", "Phase" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// 교차로 상태(Phase) 설정
  /// </summary>
  public sealed partial class IntersectionPhase : pb::IMessage<IntersectionPhase>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IntersectionPhase> _parser = new pb::MessageParser<IntersectionPhase>(() => new IntersectionPhase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IntersectionPhase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionPhase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionPhase(IntersectionPhase other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      phase_ = other.phase_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionPhase Clone() {
      return new IntersectionPhase(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier id_;
    /// <summary>
    /// 교차로 아이디
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "phase" field.</summary>
    public const int PhaseFieldNumber = 2;
    private int phase_;
    /// <summary>
    /// 변경할 교차로의 상태(Phase)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Phase {
      get { return phase_; }
      set {
        phase_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IntersectionPhase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IntersectionPhase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (Phase != other.Phase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (Phase != 0) hash ^= Phase.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (Phase != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Phase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (Phase != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Phase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (Phase != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Phase);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IntersectionPhase other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.Phase != 0) {
        Phase = other.Phase;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier();
            }
            input.ReadMessage(Id);
            break;
          }
          case 16: {
            Phase = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier();
            }
            input.ReadMessage(Id);
            break;
          }
          case 16: {
            Phase = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// 교차로 스케쥴
  /// </summary>
  public sealed partial class IntersectionSchedule : pb::IMessage<IntersectionSchedule>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IntersectionSchedule> _parser = new pb::MessageParser<IntersectionSchedule>(() => new IntersectionSchedule());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IntersectionSchedule> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionSchedule() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionSchedule(IntersectionSchedule other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      vehicle_ = other.vehicle_.Clone();
      yellow_ = other.yellow_.Clone();
      pedestrian_ = other.pedestrian_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionSchedule Clone() {
      return new IntersectionSchedule(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier id_;
    /// <summary>
    /// 교차로 아이디
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "vehicle" field.</summary>
    public const int VehicleFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Vehicle> _repeated_vehicle_codec
        = pb::FieldCodec.ForMessage(18, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Vehicle.Parser);
    private readonly pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Vehicle> vehicle_ = new pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Vehicle>();
    /// <summary>
    /// 차량 신호등 스케쥴
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Vehicle> Vehicle {
      get { return vehicle_; }
    }

    /// <summary>Field number for the "yellow" field.</summary>
    public const int YellowFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Yellow> _repeated_yellow_codec
        = pb::FieldCodec.ForMessage(26, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Yellow.Parser);
    private readonly pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Yellow> yellow_ = new pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Yellow>();
    /// <summary>
    /// 노랑 신호등 스케즁
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Yellow> Yellow {
      get { return yellow_; }
    }

    /// <summary>Field number for the "pedestrian" field.</summary>
    public const int PedestrianFieldNumber = 4;
    private static readonly pb::FieldCodec<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Pedestrian> _repeated_pedestrian_codec
        = pb::FieldCodec.ForMessage(34, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Pedestrian.Parser);
    private readonly pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Pedestrian> pedestrian_ = new pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Pedestrian>();
    /// <summary>
    /// 보행자 신호등 스케쥴
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightSchedule.Types.Pedestrian> Pedestrian {
      get { return pedestrian_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IntersectionSchedule);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IntersectionSchedule other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if(!vehicle_.Equals(other.vehicle_)) return false;
      if(!yellow_.Equals(other.yellow_)) return false;
      if(!pedestrian_.Equals(other.pedestrian_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      hash ^= vehicle_.GetHashCode();
      hash ^= yellow_.GetHashCode();
      hash ^= pedestrian_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      vehicle_.WriteTo(output, _repeated_vehicle_codec);
      yellow_.WriteTo(output, _repeated_yellow_codec);
      pedestrian_.WriteTo(output, _repeated_pedestrian_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      vehicle_.WriteTo(ref output, _repeated_vehicle_codec);
      yellow_.WriteTo(ref output, _repeated_yellow_codec);
      pedestrian_.WriteTo(ref output, _repeated_pedestrian_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      size += vehicle_.CalculateSize(_repeated_vehicle_codec);
      size += yellow_.CalculateSize(_repeated_yellow_codec);
      size += pedestrian_.CalculateSize(_repeated_pedestrian_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IntersectionSchedule other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier();
        }
        Id.MergeFrom(other.Id);
      }
      vehicle_.Add(other.vehicle_);
      yellow_.Add(other.yellow_);
      pedestrian_.Add(other.pedestrian_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            vehicle_.AddEntriesFrom(input, _repeated_vehicle_codec);
            break;
          }
          case 26: {
            yellow_.AddEntriesFrom(input, _repeated_yellow_codec);
            break;
          }
          case 34: {
            pedestrian_.AddEntriesFrom(input, _repeated_pedestrian_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectIdentifier();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            vehicle_.AddEntriesFrom(ref input, _repeated_vehicle_codec);
            break;
          }
          case 26: {
            yellow_.AddEntriesFrom(ref input, _repeated_yellow_codec);
            break;
          }
          case 34: {
            pedestrian_.AddEntriesFrom(ref input, _repeated_pedestrian_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// 교차로 상태
  /// </summary>
  public sealed partial class IntersectionState : pb::IMessage<IntersectionState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IntersectionState> _parser = new pb::MessageParser<IntersectionState>(() => new IntersectionState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IntersectionState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.IntersectionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionState(IntersectionState other) : this() {
      trafficLights_ = other.trafficLights_.Clone();
      phase_ = other.phase_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntersectionState Clone() {
      return new IntersectionState(this);
    }

    /// <summary>Field number for the "traffic_lights" field.</summary>
    public const int TrafficLightsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightInfo> _repeated_trafficLights_codec
        = pb::FieldCodec.ForMessage(10, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightInfo.Parser);
    private readonly pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightInfo> trafficLights_ = new pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightInfo>();
    /// <summary>
    /// 교차로의 신호등 정보
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Infrastructure.TrafficLightInfo> TrafficLights {
      get { return trafficLights_; }
    }

    /// <summary>Field number for the "phase" field.</summary>
    public const int PhaseFieldNumber = 2;
    private int phase_;
    /// <summary>
    /// 교차로 스케쥴 phase
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Phase {
      get { return phase_; }
      set {
        phase_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IntersectionState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IntersectionState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!trafficLights_.Equals(other.trafficLights_)) return false;
      if (Phase != other.Phase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= trafficLights_.GetHashCode();
      if (Phase != 0) hash ^= Phase.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      trafficLights_.WriteTo(output, _repeated_trafficLights_codec);
      if (Phase != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Phase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      trafficLights_.WriteTo(ref output, _repeated_trafficLights_codec);
      if (Phase != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Phase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += trafficLights_.CalculateSize(_repeated_trafficLights_codec);
      if (Phase != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Phase);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IntersectionState other) {
      if (other == null) {
        return;
      }
      trafficLights_.Add(other.trafficLights_);
      if (other.Phase != 0) {
        Phase = other.Phase;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            trafficLights_.AddEntriesFrom(input, _repeated_trafficLights_codec);
            break;
          }
          case 16: {
            Phase = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            trafficLights_.AddEntriesFrom(ref input, _repeated_trafficLights_codec);
            break;
          }
          case 16: {
            Phase = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
