// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/actor/actor.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor {

  /// <summary>Holder for reflection information generated from morai/actor/actor.proto</summary>
  public static partial class ActorReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/actor/actor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdtb3JhaS9hY3Rvci9hY3Rvci5wcm90bxITbW9yYWlfc2ltX2FwaS5hY3Rv",
            "choXbW9yYWkvY29tbW9uL3R5cGUucHJvdG8aGW1vcmFpL2NvbW1vbi9yZXN1",
            "bHQucHJvdG8aHm1vcmFpL2NvbW1vbi9vYmplY3RfaW5mby5wcm90bxodbW9y",
            "YWkvYWN0b3IvYWN0b3Jfc3Bhd24ucHJvdG8aH21vcmFpL2FjdG9yL2FjdG9y",
            "X2NvbnRyb2wucHJvdG8aG21vcmFpL2FjdG9yL2FjdG9yX2dldC5wcm90bxof",
            "bW9yYWkvYWN0b3IvYWN0b3JfbmV0d29yay5wcm90bxobbW9yYWkvYWN0b3Iv",
            "YWN0b3Jfc2V0LnByb3RvMswYCgVBY3RvchJNCgxTcGF3blZlaGljbGUSJi5t",
            "b3JhaV9zaW1fYXBpLmFjdG9yLlZlaGljbGVTcGF3blBhcmFtGhUubW9yYWlf",
            "c2ltX2FwaS5SZXN1bHQSUwoPU3Bhd25QZWRlc3RyaWFuEikubW9yYWlfc2lt",
            "X2FwaS5hY3Rvci5QZWRlc3RyaWFuU3Bhd25QYXJhbRoVLm1vcmFpX3NpbV9h",
            "cGkuUmVzdWx0Ek8KDVNwYXduT2JzdGFjbGUSJy5tb3JhaV9zaW1fYXBpLmFj",
            "dG9yLk9ic3RhY2xlU3Bhd25QYXJhbRoVLm1vcmFpX3NpbV9hcGkuUmVzdWx0",
            "EkAKDERlc3Ryb3lBY3RvchIZLm1vcmFpX3NpbV9hcGkuT2JqZWN0SW5mbxoV",
            "Lm1vcmFpX3NpbV9hcGkuUmVzdWx0EkUKEERlc3Ryb3lBbGxBY3RvcnMSGi5t",
            "b3JhaV9zaW1fYXBpLlN0cmluZ1ZhbHVlGhUubW9yYWlfc2ltX2FwaS5SZXN1",
            "bHQSTAoOQ29udHJvbFZlaGljbGUSIy5tb3JhaV9zaW1fYXBpLmFjdG9yLlZl",
            "aGljbGVDdHJsQ21kGhUubW9yYWlfc2ltX2FwaS5SZXN1bHQSUgoRQ29udHJv",
            "bFBlZGVzdHJpYW4SJi5tb3JhaV9zaW1fYXBpLmFjdG9yLlBlZGVzdHJpYW5D",
            "dHJsQ21kGhUubW9yYWlfc2ltX2FwaS5SZXN1bHQSTgoPQ29udHJvbE9ic3Rh",
            "Y2xlEiQubW9yYWlfc2ltX2FwaS5hY3Rvci5PYnN0YWNsZUN0cmxDbWQaFS5t",
            "b3JhaV9zaW1fYXBpLlJlc3VsdBJLCg1HZXRBY3RvclN0YXRlEhkubW9yYWlf",
            "c2ltX2FwaS5PYmplY3RJbmZvGh8ubW9yYWlfc2ltX2FwaS5hY3Rvci5BY3Rv",
            "clN0YXRlEl4KEUdldEFsbEFjdG9yc1N0YXRlEicubW9yYWlfc2ltX2FwaS5h",
            "Y3Rvci5HZXRBbGxBY3RvcnNGaWx0ZXIaIC5tb3JhaV9zaW1fYXBpLmFjdG9y",
            "LkFjdG9yU3RhdGVzEk0KDkdldFZlaGljbGVTcGVjEhkubW9yYWlfc2ltX2Fw",
            "aS5PYmplY3RJbmZvGiAubW9yYWlfc2ltX2FwaS5hY3Rvci5WZWhpY2xlU3Bl",
            "YxJGCg1HZXRPcHRpb25OYW1lEhkubW9yYWlfc2ltX2FwaS5PYmplY3RJbmZv",
            "GhoubW9yYWlfc2ltX2FwaS5TdHJpbmdWYWx1ZRJiChhHZXRWZWhpY2xlTmV0",
            "d29ya1NldHRpbmcSGS5tb3JhaV9zaW1fYXBpLk9iamVjdEluZm8aKy5tb3Jh",
            "aV9zaW1fYXBpLmFjdG9yLk5ldHdvcmtQcm90b2NvbFNldHRpbmcSXgoVR2V0",
            "VmVoaWNsZUNvbnRyb2xNb2RlEhkubW9yYWlfc2ltX2FwaS5PYmplY3RJbmZv",
            "GioubW9yYWlfc2ltX2FwaS5hY3Rvci5DdXJWZWhpY2xlQ29udHJvbE1vZGUS",
            "QgoIU2V0U2NhbGUSHy5tb3JhaV9zaW1fYXBpLmFjdG9yLkFjdG9yU2NhbGUa",
            "FS5tb3JhaV9zaW1fYXBpLlJlc3VsdBJNCgxTZXRUcmFuc2Zvcm0SJi5tb3Jh",
            "aV9zaW1fYXBpLmFjdG9yLlNldFRyYW5zZm9ybVBhcmFtGhUubW9yYWlfc2lt",
            "X2FwaS5SZXN1bHQSUgoUU2V0T2JzdGFjbGVBbmltYXRpb24SIy5tb3JhaV9z",
            "aW1fYXBpLmFjdG9yLkFuaW1hdGlvblBhcmFtGhUubW9yYWlfc2ltX2FwaS5S",
            "ZXN1bHQSVwoTU2V0VHJhaW5TaWduYWxMaWdodBIpLm1vcmFpX3NpbV9hcGku",
            "YWN0b3IuVHJhaW5TaWduYWxMaWdodEluZm8aFS5tb3JhaV9zaW1fYXBpLlJl",
            "c3VsdBJDCghTZXRQYXVzZRIgLm1vcmFpX3NpbV9hcGkuYWN0b3IuRW5hYmxl",
            "QWN0b3IaFS5tb3JhaV9zaW1fYXBpLlJlc3VsdBJACgVTZXRBSRIgLm1vcmFp",
            "X3NpbV9hcGkuYWN0b3IuRW5hYmxlQWN0b3IaFS5tb3JhaV9zaW1fYXBpLlJl",
            "c3VsdBJFCgpTZXRQaHlzaWNzEiAubW9yYWlfc2ltX2FwaS5hY3Rvci5FbmFi",
            "bGVBY3RvchoVLm1vcmFpX3NpbV9hcGkuUmVzdWx0EksKC1NldFZlbG9jaXR5",
            "EiUubW9yYWlfc2ltX2FwaS5hY3Rvci5TZXRWZWxvY2l0eVBhcmFtGhUubW9y",
            "YWlfc2ltX2FwaS5SZXN1bHQSTwoRU2V0VmVoaWNsZUxpbWl0ZXISIy5tb3Jh",
            "aV9zaW1fYXBpLmFjdG9yLlZlaGljbGVMaW1pdGVyGhUubW9yYWlfc2ltX2Fw",
            "aS5SZXN1bHQSWwoXU2V0VmVoaWNsZUR5bmFtaWNzU3RlZXISKS5tb3JhaV9z",
            "aW1fYXBpLmFjdG9yLlZlaGljbGVEeW5hbWljc1N0ZWVyGhUubW9yYWlfc2lt",
            "X2FwaS5SZXN1bHQSZQocU2V0VmVoaWNsZUR5bmFtaWNzU3BlZWRMaW1pdBIu",
            "Lm1vcmFpX3NpbV9hcGkuYWN0b3IuVmVoaWNsZUR5bmFtaWNzU3BlZWRMaW1p",
            "dBoVLm1vcmFpX3NpbV9hcGkuUmVzdWx0ElkKFlNldFZlaGljbGVEeW5hbWlj",
            "c01hc3MSKC5tb3JhaV9zaW1fYXBpLmFjdG9yLlZlaGljbGVEeW5hbWljc01h",
            "c3MaFS5tb3JhaV9zaW1fYXBpLlJlc3VsdBJVChRTZXRWZWhpY2xlUGF0aE9m",
            "ZnNldBImLm1vcmFpX3NpbV9hcGkuYWN0b3IuVmVoaWNsZVBhdGhPZmZzZXQa",
            "FS5tb3JhaV9zaW1fYXBpLlJlc3VsdBJXChVTZXRWZWhpY2xlRGlzdHVyYmFu",
            "Y2USJy5tb3JhaV9zaW1fYXBpLmFjdG9yLlZlaGljbGVEaXN0dXJiYW5jZRoV",
            "Lm1vcmFpX3NpbV9hcGkuUmVzdWx0El0KGFNldFZlaGljbGVGYXVsdEluamVj",
            "dGlvbhIqLm1vcmFpX3NpbV9hcGkuYWN0b3IuVmVoaWNsZUZhdWx0SW5qZWN0",
            "aW9uGhUubW9yYWlfc2ltX2FwaS5SZXN1bHQSSwoPU2V0VmVoaWNsZVJvdXRl",
            "EiEubW9yYWlfc2ltX2FwaS5hY3Rvci5WZWhpY2xlUm91dGUaFS5tb3JhaV9z",
            "aW1fYXBpLlJlc3VsdBJXChVTZXRWZWhpY2xlRGVzdGluYXRpb24SJy5tb3Jh",
            "aV9zaW1fYXBpLmFjdG9yLlZlaGljbGVEZXN0aW5hdGlvbhoVLm1vcmFpX3Np",
            "bV9hcGkuUmVzdWx0ElMKE1NldFZlaGljbGVFZ29DcnVpc2USJS5tb3JhaV9z",
            "aW1fYXBpLmFjdG9yLkVnb0NydWlzZUNvbnRyb2waFS5tb3JhaV9zaW1fYXBp",
            "LlJlc3VsdBJOChFTZXRWZWhpY2xlTmV0d29yaxIiLm1vcmFpX3NpbV9hcGku",
            "YWN0b3IuTmV0d29ya0NvbmZpZxoVLm1vcmFpX3NpbV9hcGkuUmVzdWx0EksK",
            "D1NldFZlaGljbGVTdGVlchIhLm1vcmFpX3NpbV9hcGkuYWN0b3IuVmVoaWNs",
            "ZVN0ZWVyGhUubW9yYWlfc2ltX2FwaS5SZXN1bHQSXAoVU2V0VmVoaWNsZUNv",
            "bnRyb2xNb2RlEiwubW9yYWlfc2ltX2FwaS5hY3Rvci5WZWhpY2xlQ29udHJv",
            "bE1vZGVQYXJhbRoVLm1vcmFpX3NpbV9hcGkuUmVzdWx0EkkKDlNldFZlaGlj",
            "bGVHZWFyEiAubW9yYWlfc2ltX2FwaS5hY3Rvci5WZWhpY2xlR2VhchoVLm1v",
            "cmFpX3NpbV9hcGkuUmVzdWx0ElMKE1NldFZlaGljbGVUYWlsTGlnaHQSJS5t",
            "b3JhaV9zaW1fYXBpLmFjdG9yLlZlaGljbGVUYWlsTGlnaHQaFS5tb3JhaV9z",
            "aW1fYXBpLlJlc3VsdBJbChVTZXRQZWRlc3RyaWFuV2F5cG9pbnQSKy5tb3Jh",
            "aV9zaW1fYXBpLmFjdG9yLlBlZGVzdHJpYW5XYXlwb2ludEluZm8aFS5tb3Jh",
            "aV9zaW1fYXBpLlJlc3VsdEIsSAGqAidDb3JlTGliLkdycGMuUHJvdG9idWYu",
            "TW9yYWlTaW1BUEkuQWN0b3JiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CoreLib.Grpc.Protobuf.MoraiSimAPI.TypeReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ResultReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectInfoReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.ActorSpawnReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.ActorControlReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.ActorGetReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.ActorNetworkReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.ActorSetReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
