// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/common/enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI {

  /// <summary>Holder for reflection information generated from morai/common/enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/common/enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdtb3JhaS9jb21tb24vZW51bS5wcm90bxINbW9yYWlfc2ltX2FwaSpGCgpT",
            "dGF0dXNDb2RlEh8KG1NUQVRVU19DT0RFX1VOS05PV05fRkFJTFVSRRAAEhcK",
            "E1NUQVRVU19DT0RFX1NVQ0NFU1MQASqVAQoKT2JqZWN0VHlwZRIbChdPQkpF",
            "Q1RfVFlQRV9VTlNQRUNJRklFRBAAEhcKE09CSkVDVF9UWVBFX1ZFSElDTEUQ",
            "ARIaChZPQkpFQ1RfVFlQRV9QRURFU1RSSUFOEAISGAoUT0JKRUNUX1RZUEVf",
            "T0JTVEFDTEUQAxIbChdPQkpFQ1RfVFlQRV9TUEFXTl9QT0lOVBAEQiZIAaoC",
            "IUNvcmVMaWIuR3JwYy5Qcm90b2J1Zi5Nb3JhaVNpbUFQSWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.StatusCode), typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum StatusCode {
    /// <summary>
    /// MORAI SIM side에서 실패
    /// </summary>
    [pbr::OriginalName("STATUS_CODE_UNKNOWN_FAILURE")] UnknownFailure = 0,
    /// <summary>
    /// rpc 호출 성공
    /// </summary>
    [pbr::OriginalName("STATUS_CODE_SUCCESS")] Success = 1,
  }

  public enum ObjectType {
    [pbr::OriginalName("OBJECT_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("OBJECT_TYPE_VEHICLE")] Vehicle = 1,
    [pbr::OriginalName("OBJECT_TYPE_PEDESTRIAN")] Pedestrian = 2,
    [pbr::OriginalName("OBJECT_TYPE_OBSTACLE")] Obstacle = 3,
    [pbr::OriginalName("OBJECT_TYPE_SPAWN_POINT")] SpawnPoint = 4,
  }

  #endregion

}

#endregion Designer generated code
