// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/sensor/sensor_data_save_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor {

  /// <summary>Holder for reflection information generated from morai/sensor/sensor_data_save_config.proto</summary>
  public static partial class SensorDataSaveConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/sensor/sensor_data_save_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SensorDataSaveConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ciptb3JhaS9zZW5zb3Ivc2Vuc29yX2RhdGFfc2F2ZV9jb25maWcucHJvdG8S",
            "FG1vcmFpX3NpbV9hcGkuc2Vuc29yIl8KFFNlbnNvckRhdGFTYXZlQ29uZmln",
            "EhsKE2lzX2N1c3RvbV9maWxlX25hbWUYASABKAgSGAoQY3VzdG9tX2ZpbGVf",
            "bmFtZRgCIAEoCRIQCghmaWxlX2RpchgDIAEoCUItSAGqAihDb3JlTGliLkdy",
            "cGMuUHJvdG9idWYuTW9yYWlTaW1BUEkuU2Vuc29yYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor.SensorDataSaveConfig), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor.SensorDataSaveConfig.Parser, new[]{ "IsCustomFileName", "CustomFileName", "FileDir" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// MORAI SIM 의 센서 데이터 저장 기능을 이용해 센서 데이터를 저장하기 위한 설정
  /// </summary>
  public sealed partial class SensorDataSaveConfig : pb::IMessage<SensorDataSaveConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SensorDataSaveConfig> _parser = new pb::MessageParser<SensorDataSaveConfig>(() => new SensorDataSaveConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SensorDataSaveConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor.SensorDataSaveConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorDataSaveConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorDataSaveConfig(SensorDataSaveConfig other) : this() {
      isCustomFileName_ = other.isCustomFileName_;
      customFileName_ = other.customFileName_;
      fileDir_ = other.fileDir_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SensorDataSaveConfig Clone() {
      return new SensorDataSaveConfig(this);
    }

    /// <summary>Field number for the "is_custom_file_name" field.</summary>
    public const int IsCustomFileNameFieldNumber = 1;
    private bool isCustomFileName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCustomFileName {
      get { return isCustomFileName_; }
      set {
        isCustomFileName_ = value;
      }
    }

    /// <summary>Field number for the "custom_file_name" field.</summary>
    public const int CustomFileNameFieldNumber = 2;
    private string customFileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CustomFileName {
      get { return customFileName_; }
      set {
        customFileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "file_dir" field.</summary>
    public const int FileDirFieldNumber = 3;
    private string fileDir_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileDir {
      get { return fileDir_; }
      set {
        fileDir_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SensorDataSaveConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SensorDataSaveConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsCustomFileName != other.IsCustomFileName) return false;
      if (CustomFileName != other.CustomFileName) return false;
      if (FileDir != other.FileDir) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsCustomFileName != false) hash ^= IsCustomFileName.GetHashCode();
      if (CustomFileName.Length != 0) hash ^= CustomFileName.GetHashCode();
      if (FileDir.Length != 0) hash ^= FileDir.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsCustomFileName != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsCustomFileName);
      }
      if (CustomFileName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CustomFileName);
      }
      if (FileDir.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FileDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsCustomFileName != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsCustomFileName);
      }
      if (CustomFileName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CustomFileName);
      }
      if (FileDir.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FileDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsCustomFileName != false) {
        size += 1 + 1;
      }
      if (CustomFileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomFileName);
      }
      if (FileDir.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileDir);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SensorDataSaveConfig other) {
      if (other == null) {
        return;
      }
      if (other.IsCustomFileName != false) {
        IsCustomFileName = other.IsCustomFileName;
      }
      if (other.CustomFileName.Length != 0) {
        CustomFileName = other.CustomFileName;
      }
      if (other.FileDir.Length != 0) {
        FileDir = other.FileDir;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsCustomFileName = input.ReadBool();
            break;
          }
          case 18: {
            CustomFileName = input.ReadString();
            break;
          }
          case 26: {
            FileDir = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsCustomFileName = input.ReadBool();
            break;
          }
          case 18: {
            CustomFileName = input.ReadString();
            break;
          }
          case 26: {
            FileDir = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
