// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/sensor/sensor_enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor {

  /// <summary>Holder for reflection information generated from morai/sensor/sensor_enum.proto</summary>
  public static partial class SensorEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/sensor/sensor_enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SensorEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5tb3JhaS9zZW5zb3Ivc2Vuc29yX2VudW0ucHJvdG8SFG1vcmFpX3NpbV9h",
            "cGkuc2Vuc29yKoICCgpTZW5zb3JUeXBlEhsKF1NFTlNPUl9UWVBFX1VOU1BF",
            "Q0lGSUVEEAASFgoSU0VOU09SX1RZUEVfQ0FNRVJBEAESFwoTU0VOU09SX1RZ",
            "UEVfTElEQVIzRBACEhcKE1NFTlNPUl9UWVBFX0xJREFSMkQQAxITCg9TRU5T",
            "T1JfVFlQRV9HUFMQBBITCg9TRU5TT1JfVFlQRV9JTVUQBRIVChFTRU5TT1Jf",
            "VFlQRV9SQURBUhAGEhoKFlNFTlNPUl9UWVBFX1VMVFJBU09OSUMQBxIbChdT",
            "RU5TT1JfVFlQRV9HUk9VTkRUUlVUSBAIEhMKD1NFTlNPUl9UWVBFX0VORBAJ",
            "KmMKC0dUU2hhcGVUeXBlEhgKFEdUX1NIQVBFX1VOU1BFQ0lGSUVEEAASFQoR",
            "R1RfU0hBUEVfQ1lMSU5ERVIQARIRCg1HVF9TSEFQRV9DT05FEAISEAoMR1Rf",
            "U0hBUEVfRU5EEAMq+AMKEUdUT2JzdGFjbGVPYmpUeXBlEhsKF0dUX09CU1RB",
            "Q0xFX09CSl9JTktOT1dOEAASGwoXR1RfT0JTVEFDTEVfT0JKX1ZFSElDTEUQ",
            "ARIeChpHVF9PQlNUQUNMRV9PQkpfUEVERVNUUklBThACEh4KGkdUX09CU1RB",
            "Q0xFX09CSl9FR09WRUhJQ0xFEAMSHAoYR1RfT0JTVEFDTEVfT0JKX09CU1RB",
            "Q0xFEAQSHgoaR1RfT0JTVEFDTEVfT0JKX1NQQVdOUE9JTlQQBRIgChxHVF9P",
            "QlNUQUNMRV9PQkpfTU9WSU5HT0JKRUNUEAYSIQodR1RfT0JTVEFDTEVfT0JK",
            "X0VYVFJBT0JTVEFDTEUQBxIjCh9HVF9PQlNUQUNMRV9PQkpfU1NBRllTUEFX",
            "TlBPSU5UEAgSJAogR1RfT0JTVEFDTEVfT0JKX0RFU1RJTkFUSU9OUE9JTlQQ",
            "CRIhCh1HVF9PQlNUQUNMRV9PQkpfU1RPUE9WRVJQT0lOVBAKEiEKHUdUX09C",
            "U1RBQ0xFX09CSl9QRURTUEFXTlBPSU5UEAsSHgoaR1RfT0JTVEFDTEVfT0JK",
            "X1NIQURFREFSRUEQDBIdChlHVF9PQlNUQUNMRV9PQkpfTUFQT0JKRUNUEA0S",
            "FgoSR1RfT0JTVEFDTF9PQkpfTUFYEA5CLUgBqgIoQ29yZUxpYi5HcnBjLlBy",
            "b3RvYnVmLk1vcmFpU2ltQVBJLlNlbnNvcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor.SensorType), typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor.GTShapeType), typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Sensor.GTObstacleObjType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum SensorType {
    [pbr::OriginalName("SENSOR_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("SENSOR_TYPE_CAMERA")] Camera = 1,
    [pbr::OriginalName("SENSOR_TYPE_LIDAR3D")] Lidar3D = 2,
    [pbr::OriginalName("SENSOR_TYPE_LIDAR2D")] Lidar2D = 3,
    [pbr::OriginalName("SENSOR_TYPE_GPS")] Gps = 4,
    [pbr::OriginalName("SENSOR_TYPE_IMU")] Imu = 5,
    [pbr::OriginalName("SENSOR_TYPE_RADAR")] Radar = 6,
    [pbr::OriginalName("SENSOR_TYPE_ULTRASONIC")] Ultrasonic = 7,
    [pbr::OriginalName("SENSOR_TYPE_GROUNDTRUTH")] Groundtruth = 8,
    [pbr::OriginalName("SENSOR_TYPE_END")] End = 9,
  }

  public enum GTShapeType {
    [pbr::OriginalName("GT_SHAPE_UNSPECIFIED")] GtShapeUnspecified = 0,
    [pbr::OriginalName("GT_SHAPE_CYLINDER")] GtShapeCylinder = 1,
    [pbr::OriginalName("GT_SHAPE_CONE")] GtShapeCone = 2,
    [pbr::OriginalName("GT_SHAPE_END")] GtShapeEnd = 3,
  }

  public enum GTObstacleObjType {
    [pbr::OriginalName("GT_OBSTACLE_OBJ_INKNOWN")] GtObstacleObjInknown = 0,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_VEHICLE")] GtObstacleObjVehicle = 1,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_PEDESTRIAN")] GtObstacleObjPedestrian = 2,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_EGOVEHICLE")] GtObstacleObjEgovehicle = 3,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_OBSTACLE")] GtObstacleObjObstacle = 4,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_SPAWNPOINT")] GtObstacleObjSpawnpoint = 5,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_MOVINGOBJECT")] GtObstacleObjMovingobject = 6,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_EXTRAOBSTACLE")] GtObstacleObjExtraobstacle = 7,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_SSAFYSPAWNPOINT")] GtObstacleObjSsafyspawnpoint = 8,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_DESTINATIONPOINT")] GtObstacleObjDestinationpoint = 9,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_STOPOVERPOINT")] GtObstacleObjStopoverpoint = 10,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_PEDSPAWNPOINT")] GtObstacleObjPedspawnpoint = 11,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_SHADEDAREA")] GtObstacleObjShadedarea = 12,
    [pbr::OriginalName("GT_OBSTACLE_OBJ_MAPOBJECT")] GtObstacleObjMapobject = 13,
    [pbr::OriginalName("GT_OBSTACL_OBJ_MAX")] GtObstaclObjMax = 14,
  }

  #endregion

}

#endregion Designer generated code
