// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/scenario/scenario_object.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario {

  /// <summary>Holder for reflection information generated from morai/scenario/scenario_object.proto</summary>
  public static partial class ScenarioObjectReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/scenario/scenario_object.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScenarioObjectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRtb3JhaS9zY2VuYXJpby9zY2VuYXJpb19vYmplY3QucHJvdG8SFm1vcmFp",
            "X3NpbV9hcGkuc2NlbmFyaW8aF21vcmFpL2NvbW1vbi90eXBlLnByb3RvGh5t",
            "b3JhaS9jb21tb24vb2JqZWN0X2luZm8ucHJvdG8i6gEKHkNyZWF0ZUZyaWN0",
            "aW9uQ29udHJvbEFyZWFQYXJhbRIuCgtvYmplY3RfaW5mbxgBIAEoCzIZLm1v",
            "cmFpX3NpbV9hcGkuT2JqZWN0SW5mbxIrCgl0cmFuc2Zvcm0YAiABKAsyGC5t",
            "b3JhaV9zaW1fYXBpLlRyYW5zZm9ybRITCgtvYmplY3RfbmFtZRgDIAEoCRIX",
            "Cg92ZXJ0aWNhbF9yYWRpdXMYBCABKAISGQoRaG9yaXpvbnRhbF9yYWRpdXMY",
            "BSABKAISDgoGaGVpZ2h0GAYgASgCEhIKCm11bHRpcGxpZXIYByABKAJCL0gB",
            "qgIqQ29yZUxpYi5HcnBjLlByb3RvYnVmLk1vcmFpU2ltQVBJLlNjZW5hcmlv",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CoreLib.Grpc.Protobuf.MoraiSimAPI.TypeReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario.CreateFrictionControlAreaParam), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario.CreateFrictionControlAreaParam.Parser, new[]{ "ObjectInfo", "Transform", "ObjectName", "VerticalRadius", "HorizontalRadius", "Height", "Multiplier" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CreateFrictionControlAreaParam : pb::IMessage<CreateFrictionControlAreaParam>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateFrictionControlAreaParam> _parser = new pb::MessageParser<CreateFrictionControlAreaParam>(() => new CreateFrictionControlAreaParam());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateFrictionControlAreaParam> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario.ScenarioObjectReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateFrictionControlAreaParam() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateFrictionControlAreaParam(CreateFrictionControlAreaParam other) : this() {
      objectInfo_ = other.objectInfo_ != null ? other.objectInfo_.Clone() : null;
      transform_ = other.transform_ != null ? other.transform_.Clone() : null;
      objectName_ = other.objectName_;
      verticalRadius_ = other.verticalRadius_;
      horizontalRadius_ = other.horizontalRadius_;
      height_ = other.height_;
      multiplier_ = other.multiplier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateFrictionControlAreaParam Clone() {
      return new CreateFrictionControlAreaParam(this);
    }

    /// <summary>Field number for the "object_info" field.</summary>
    public const int ObjectInfoFieldNumber = 1;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectInfo objectInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectInfo ObjectInfo {
      get { return objectInfo_; }
      set {
        objectInfo_ = value;
      }
    }

    /// <summary>Field number for the "transform" field.</summary>
    public const int TransformFieldNumber = 2;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform transform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform Transform {
      get { return transform_; }
      set {
        transform_ = value;
      }
    }

    /// <summary>Field number for the "object_name" field.</summary>
    public const int ObjectNameFieldNumber = 3;
    private string objectName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObjectName {
      get { return objectName_; }
      set {
        objectName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "vertical_radius" field.</summary>
    public const int VerticalRadiusFieldNumber = 4;
    private float verticalRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VerticalRadius {
      get { return verticalRadius_; }
      set {
        verticalRadius_ = value;
      }
    }

    /// <summary>Field number for the "horizontal_radius" field.</summary>
    public const int HorizontalRadiusFieldNumber = 5;
    private float horizontalRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float HorizontalRadius {
      get { return horizontalRadius_; }
      set {
        horizontalRadius_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 6;
    private float height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "multiplier" field.</summary>
    public const int MultiplierFieldNumber = 7;
    private float multiplier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Multiplier {
      get { return multiplier_; }
      set {
        multiplier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateFrictionControlAreaParam);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateFrictionControlAreaParam other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ObjectInfo, other.ObjectInfo)) return false;
      if (!object.Equals(Transform, other.Transform)) return false;
      if (ObjectName != other.ObjectName) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VerticalRadius, other.VerticalRadius)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(HorizontalRadius, other.HorizontalRadius)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Height, other.Height)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Multiplier, other.Multiplier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (objectInfo_ != null) hash ^= ObjectInfo.GetHashCode();
      if (transform_ != null) hash ^= Transform.GetHashCode();
      if (ObjectName.Length != 0) hash ^= ObjectName.GetHashCode();
      if (VerticalRadius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VerticalRadius);
      if (HorizontalRadius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(HorizontalRadius);
      if (Height != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Height);
      if (Multiplier != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Multiplier);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (objectInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectInfo);
      }
      if (transform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transform);
      }
      if (ObjectName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ObjectName);
      }
      if (VerticalRadius != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(VerticalRadius);
      }
      if (HorizontalRadius != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(HorizontalRadius);
      }
      if (Height != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Height);
      }
      if (Multiplier != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Multiplier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (objectInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ObjectInfo);
      }
      if (transform_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transform);
      }
      if (ObjectName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ObjectName);
      }
      if (VerticalRadius != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(VerticalRadius);
      }
      if (HorizontalRadius != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(HorizontalRadius);
      }
      if (Height != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Height);
      }
      if (Multiplier != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Multiplier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (objectInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ObjectInfo);
      }
      if (transform_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transform);
      }
      if (ObjectName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObjectName);
      }
      if (VerticalRadius != 0F) {
        size += 1 + 4;
      }
      if (HorizontalRadius != 0F) {
        size += 1 + 4;
      }
      if (Height != 0F) {
        size += 1 + 4;
      }
      if (Multiplier != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateFrictionControlAreaParam other) {
      if (other == null) {
        return;
      }
      if (other.objectInfo_ != null) {
        if (objectInfo_ == null) {
          ObjectInfo = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectInfo();
        }
        ObjectInfo.MergeFrom(other.ObjectInfo);
      }
      if (other.transform_ != null) {
        if (transform_ == null) {
          Transform = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform();
        }
        Transform.MergeFrom(other.Transform);
      }
      if (other.ObjectName.Length != 0) {
        ObjectName = other.ObjectName;
      }
      if (other.VerticalRadius != 0F) {
        VerticalRadius = other.VerticalRadius;
      }
      if (other.HorizontalRadius != 0F) {
        HorizontalRadius = other.HorizontalRadius;
      }
      if (other.Height != 0F) {
        Height = other.Height;
      }
      if (other.Multiplier != 0F) {
        Multiplier = other.Multiplier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (objectInfo_ == null) {
              ObjectInfo = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectInfo();
            }
            input.ReadMessage(ObjectInfo);
            break;
          }
          case 18: {
            if (transform_ == null) {
              Transform = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform();
            }
            input.ReadMessage(Transform);
            break;
          }
          case 26: {
            ObjectName = input.ReadString();
            break;
          }
          case 37: {
            VerticalRadius = input.ReadFloat();
            break;
          }
          case 45: {
            HorizontalRadius = input.ReadFloat();
            break;
          }
          case 53: {
            Height = input.ReadFloat();
            break;
          }
          case 61: {
            Multiplier = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (objectInfo_ == null) {
              ObjectInfo = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ObjectInfo();
            }
            input.ReadMessage(ObjectInfo);
            break;
          }
          case 18: {
            if (transform_ == null) {
              Transform = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform();
            }
            input.ReadMessage(Transform);
            break;
          }
          case 26: {
            ObjectName = input.ReadString();
            break;
          }
          case 37: {
            VerticalRadius = input.ReadFloat();
            break;
          }
          case 45: {
            HorizontalRadius = input.ReadFloat();
            break;
          }
          case 53: {
            Height = input.ReadFloat();
            break;
          }
          case 61: {
            Multiplier = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
