// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/scenario/scenario.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario {

  /// <summary>Holder for reflection information generated from morai/scenario/scenario.proto</summary>
  public static partial class ScenarioReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/scenario/scenario.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScenarioReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1tb3JhaS9zY2VuYXJpby9zY2VuYXJpby5wcm90bxIWbW9yYWlfc2ltX2Fw",
            "aS5zY2VuYXJpbxoXbW9yYWkvY29tbW9uL3R5cGUucHJvdG8aGW1vcmFpL2Nv",
            "bW1vbi9yZXN1bHQucHJvdG8aIG1vcmFpL3NjZW5hcmlvL3NwYXduX3BvaW50",
            "LnByb3RvGiRtb3JhaS9zY2VuYXJpby9zY2VuYXJpb19vYmplY3QucHJvdG8y",
            "7gMKCFNjZW5hcmlvEkYKEUxvYWRNb3JhaVNjZW5hcmlvEhoubW9yYWlfc2lt",
            "X2FwaS5TdHJpbmdWYWx1ZRoVLm1vcmFpX3NpbV9hcGkuUmVzdWx0EmYKF0Ny",
            "ZWF0ZVZlaGljbGVTcGF3blBvaW50EjQubW9yYWlfc2ltX2FwaS5zY2VuYXJp",
            "by5DcmVhdGVWZWhpY2xlU3Bhd25Qb2ludFBhcmFtGhUubW9yYWlfc2ltX2Fw",
            "aS5SZXN1bHQSbAoaQ3JlYXRlUGVkZXN0cmlhblNwYXduUG9pbnQSNy5tb3Jh",
            "aV9zaW1fYXBpLnNjZW5hcmlvLkNyZWF0ZVBlZGVzdHJpYW5TcGF3blBvaW50",
            "UGFyYW0aFS5tb3JhaV9zaW1fYXBpLlJlc3VsdBJYChBFbmFibGVTcGF3blBv",
            "aW50Ei0ubW9yYWlfc2ltX2FwaS5zY2VuYXJpby5FbmFibGVTcGF3blBvaW50",
            "UGFyYW0aFS5tb3JhaV9zaW1fYXBpLlJlc3VsdBJqChlDcmVhdGVGcmljdGlv",
            "bkNvbnRyb2xBcmVhEjYubW9yYWlfc2ltX2FwaS5zY2VuYXJpby5DcmVhdGVG",
            "cmljdGlvbkNvbnRyb2xBcmVhUGFyYW0aFS5tb3JhaV9zaW1fYXBpLlJlc3Vs",
            "dEIvSAGqAipDb3JlTGliLkdycGMuUHJvdG9idWYuTW9yYWlTaW1BUEkuU2Nl",
            "bmFyaW9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CoreLib.Grpc.Protobuf.MoraiSimAPI.TypeReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.ResultReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario.SpawnPointReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Scenario.ScenarioObjectReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
