// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: morai/simulation/start_param.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation {

  /// <summary>Holder for reflection information generated from morai/simulation/start_param.proto</summary>
  public static partial class StartParamReflection {

    #region Descriptor
    /// <summary>File descriptor for morai/simulation/start_param.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StartParamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJtb3JhaS9zaW11bGF0aW9uL3N0YXJ0X3BhcmFtLnByb3RvEhhtb3JhaV9z",
            "aW1fYXBpLnNpbXVsYXRpb24aF21vcmFpL2NvbW1vbi90eXBlLnByb3RvGiBt",
            "b3JhaS9zaW11bGF0aW9uL3N5bmNfbW9kZS5wcm90bxobbW9yYWkvYWN0b3Iv",
            "YWN0b3Jfc2V0LnByb3RvGiZtb3JhaS9zaW11bGF0aW9uL3NpbXVsYXRpb25f",
            "ZW51bS5wcm90byKJAwoKU3RhcnRQYXJhbRJACg9tYXBfYW5kX3ZlaGljbGUY",
            "ASABKAsyJy5tb3JhaV9zaW1fYXBpLnNpbXVsYXRpb24uTWFwQW5kVmVoaWNs",
            "ZRI0CgtlZ29fc2V0dGluZxgCIAEoCzIfLm1vcmFpX3NpbV9hcGkuYWN0b3Iu",
            "RWdvU2V0dGluZxIvCg1lZ29fdHJhbnNmb3JtGAMgASgLMhgubW9yYWlfc2lt",
            "X2FwaS5UcmFuc2Zvcm0SQQoSZWdvX2NydWlzZV9zZXR0aW5nGAQgASgLMiUu",
            "bW9yYWlfc2ltX2FwaS5hY3Rvci5FZ29DcnVpc2VDb250cm9sEjAKBG1vZGUY",
            "BSABKAsyIi5tb3JhaV9zaW1fYXBpLnNpbXVsYXRpb24uU3luY01vZGUSSQoT",
            "c2ltdWxhdGlvbl9zZXR0aW5ncxgHIAEoCzIsLm1vcmFpX3NpbV9hcGkuc2lt",
            "dWxhdGlvbi5TaW11bGF0aW9uU2V0dGluZ3MSEgoKY2xpZW50X2tleRgIIAEo",
            "CSI8Cg1NYXBBbmRWZWhpY2xlEhAKCG1hcF9uYW1lGAEgASgJEhkKEWVnb192",
            "ZWhpY2xlX21vZGVsGAIgASgJIlYKElNpbXVsYXRpb25TZXR0aW5ncxIfChdt",
            "b3JhaV9zY2VuYXJpb19maWxlbmFtZRgBIAEoCRIfChdzZW5zb3Jfc2V0dGlu",
            "Z19maWxlbmFtZRgCIAEoCSJRChNTaW11bGF0aW9uTW9kZVBhcmFtEjoKBG1v",
            "ZGUYASABKA4yLC5tb3JhaV9zaW1fYXBpLnNpbXVsYXRpb24uU2ltdWxhdGlv",
            "bk1vZGVUeXBlIjEKEFNlbmRNZXNzYWdlUGFyYW0SDAoEdHlwZRgBIAEoDRIP",
            "CgdtZXNzYWdlGAIgASgJQjFIAaoCLENvcmVMaWIuR3JwYy5Qcm90b2J1Zi5N",
            "b3JhaVNpbUFQSS5TaW11bGF0aW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CoreLib.Grpc.Protobuf.MoraiSimAPI.TypeReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SyncModeReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.ActorSetReflection.Descriptor, global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationEnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.StartParam), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.StartParam.Parser, new[]{ "MapAndVehicle", "EgoSetting", "EgoTransform", "EgoCruiseSetting", "Mode", "SimulationSettings", "ClientKey" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.MapAndVehicle), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.MapAndVehicle.Parser, new[]{ "MapName", "EgoVehicleModel" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationSettings), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationSettings.Parser, new[]{ "MoraiScenarioFilename", "SensorSettingFilename" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeParam), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeParam.Parser, new[]{ "Mode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SendMessageParam), global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SendMessageParam.Parser, new[]{ "Type", "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// 시뮬레이션을 시작하기 위해 필요한 설정
  /// </summary>
  public sealed partial class StartParam : pb::IMessage<StartParam>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StartParam> _parser = new pb::MessageParser<StartParam>(() => new StartParam());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StartParam> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.StartParamReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartParam() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartParam(StartParam other) : this() {
      mapAndVehicle_ = other.mapAndVehicle_ != null ? other.mapAndVehicle_.Clone() : null;
      egoSetting_ = other.egoSetting_ != null ? other.egoSetting_.Clone() : null;
      egoTransform_ = other.egoTransform_ != null ? other.egoTransform_.Clone() : null;
      egoCruiseSetting_ = other.egoCruiseSetting_ != null ? other.egoCruiseSetting_.Clone() : null;
      mode_ = other.mode_ != null ? other.mode_.Clone() : null;
      simulationSettings_ = other.simulationSettings_ != null ? other.simulationSettings_.Clone() : null;
      clientKey_ = other.clientKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartParam Clone() {
      return new StartParam(this);
    }

    /// <summary>Field number for the "map_and_vehicle" field.</summary>
    public const int MapAndVehicleFieldNumber = 1;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.MapAndVehicle mapAndVehicle_;
    /// <summary>
    /// 시뮬레이션을 진행할 지도와 Ego차량 설정
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.MapAndVehicle MapAndVehicle {
      get { return mapAndVehicle_; }
      set {
        mapAndVehicle_ = value;
      }
    }

    /// <summary>Field number for the "ego_setting" field.</summary>
    public const int EgoSettingFieldNumber = 2;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoSetting egoSetting_;
    /// <summary>
    /// Ego 차량의 label, id 설정
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoSetting EgoSetting {
      get { return egoSetting_; }
      set {
        egoSetting_ = value;
      }
    }

    /// <summary>Field number for the "ego_transform" field.</summary>
    public const int EgoTransformFieldNumber = 3;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform egoTransform_;
    /// <summary>
    /// Ego 차량의 transform 설정
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform EgoTransform {
      get { return egoTransform_; }
      set {
        egoTransform_ = value;
      }
    }

    /// <summary>Field number for the "ego_cruise_setting" field.</summary>
    public const int EgoCruiseSettingFieldNumber = 4;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoCruiseControl egoCruiseSetting_;
    /// <summary>
    /// Ego 차량의 cruise 설정
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoCruiseControl EgoCruiseSetting {
      get { return egoCruiseSetting_; }
      set {
        egoCruiseSetting_ = value;
      }
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 5;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SyncMode mode_;
    /// <summary>
    /// Synchronous 모드 설정
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SyncMode Mode {
      get { return mode_; }
      set {
        mode_ = value;
      }
    }

    /// <summary>Field number for the "simulation_settings" field.</summary>
    public const int SimulationSettingsFieldNumber = 7;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationSettings simulationSettings_;
    /// <summary>
    /// 시뮬레이션 설정 (시나리오, 센서 설정)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationSettings SimulationSettings {
      get { return simulationSettings_; }
      set {
        simulationSettings_ = value;
      }
    }

    /// <summary>Field number for the "client_key" field.</summary>
    public const int ClientKeyFieldNumber = 8;
    private string clientKey_ = "";
    /// <summary>
    /// Client에서 생성한 임의의 문자열로, 이 문자열로 생성한 Actor를 삭제한다.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientKey {
      get { return clientKey_; }
      set {
        clientKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StartParam);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StartParam other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MapAndVehicle, other.MapAndVehicle)) return false;
      if (!object.Equals(EgoSetting, other.EgoSetting)) return false;
      if (!object.Equals(EgoTransform, other.EgoTransform)) return false;
      if (!object.Equals(EgoCruiseSetting, other.EgoCruiseSetting)) return false;
      if (!object.Equals(Mode, other.Mode)) return false;
      if (!object.Equals(SimulationSettings, other.SimulationSettings)) return false;
      if (ClientKey != other.ClientKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (mapAndVehicle_ != null) hash ^= MapAndVehicle.GetHashCode();
      if (egoSetting_ != null) hash ^= EgoSetting.GetHashCode();
      if (egoTransform_ != null) hash ^= EgoTransform.GetHashCode();
      if (egoCruiseSetting_ != null) hash ^= EgoCruiseSetting.GetHashCode();
      if (mode_ != null) hash ^= Mode.GetHashCode();
      if (simulationSettings_ != null) hash ^= SimulationSettings.GetHashCode();
      if (ClientKey.Length != 0) hash ^= ClientKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (mapAndVehicle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MapAndVehicle);
      }
      if (egoSetting_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EgoSetting);
      }
      if (egoTransform_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(EgoTransform);
      }
      if (egoCruiseSetting_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(EgoCruiseSetting);
      }
      if (mode_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Mode);
      }
      if (simulationSettings_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(SimulationSettings);
      }
      if (ClientKey.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ClientKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (mapAndVehicle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MapAndVehicle);
      }
      if (egoSetting_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EgoSetting);
      }
      if (egoTransform_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(EgoTransform);
      }
      if (egoCruiseSetting_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(EgoCruiseSetting);
      }
      if (mode_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Mode);
      }
      if (simulationSettings_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(SimulationSettings);
      }
      if (ClientKey.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ClientKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (mapAndVehicle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapAndVehicle);
      }
      if (egoSetting_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EgoSetting);
      }
      if (egoTransform_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EgoTransform);
      }
      if (egoCruiseSetting_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EgoCruiseSetting);
      }
      if (mode_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mode);
      }
      if (simulationSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SimulationSettings);
      }
      if (ClientKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StartParam other) {
      if (other == null) {
        return;
      }
      if (other.mapAndVehicle_ != null) {
        if (mapAndVehicle_ == null) {
          MapAndVehicle = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.MapAndVehicle();
        }
        MapAndVehicle.MergeFrom(other.MapAndVehicle);
      }
      if (other.egoSetting_ != null) {
        if (egoSetting_ == null) {
          EgoSetting = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoSetting();
        }
        EgoSetting.MergeFrom(other.EgoSetting);
      }
      if (other.egoTransform_ != null) {
        if (egoTransform_ == null) {
          EgoTransform = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform();
        }
        EgoTransform.MergeFrom(other.EgoTransform);
      }
      if (other.egoCruiseSetting_ != null) {
        if (egoCruiseSetting_ == null) {
          EgoCruiseSetting = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoCruiseControl();
        }
        EgoCruiseSetting.MergeFrom(other.EgoCruiseSetting);
      }
      if (other.mode_ != null) {
        if (mode_ == null) {
          Mode = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SyncMode();
        }
        Mode.MergeFrom(other.Mode);
      }
      if (other.simulationSettings_ != null) {
        if (simulationSettings_ == null) {
          SimulationSettings = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationSettings();
        }
        SimulationSettings.MergeFrom(other.SimulationSettings);
      }
      if (other.ClientKey.Length != 0) {
        ClientKey = other.ClientKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mapAndVehicle_ == null) {
              MapAndVehicle = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.MapAndVehicle();
            }
            input.ReadMessage(MapAndVehicle);
            break;
          }
          case 18: {
            if (egoSetting_ == null) {
              EgoSetting = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoSetting();
            }
            input.ReadMessage(EgoSetting);
            break;
          }
          case 26: {
            if (egoTransform_ == null) {
              EgoTransform = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform();
            }
            input.ReadMessage(EgoTransform);
            break;
          }
          case 34: {
            if (egoCruiseSetting_ == null) {
              EgoCruiseSetting = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoCruiseControl();
            }
            input.ReadMessage(EgoCruiseSetting);
            break;
          }
          case 42: {
            if (mode_ == null) {
              Mode = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SyncMode();
            }
            input.ReadMessage(Mode);
            break;
          }
          case 58: {
            if (simulationSettings_ == null) {
              SimulationSettings = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationSettings();
            }
            input.ReadMessage(SimulationSettings);
            break;
          }
          case 66: {
            ClientKey = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (mapAndVehicle_ == null) {
              MapAndVehicle = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.MapAndVehicle();
            }
            input.ReadMessage(MapAndVehicle);
            break;
          }
          case 18: {
            if (egoSetting_ == null) {
              EgoSetting = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoSetting();
            }
            input.ReadMessage(EgoSetting);
            break;
          }
          case 26: {
            if (egoTransform_ == null) {
              EgoTransform = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Transform();
            }
            input.ReadMessage(EgoTransform);
            break;
          }
          case 34: {
            if (egoCruiseSetting_ == null) {
              EgoCruiseSetting = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Actor.EgoCruiseControl();
            }
            input.ReadMessage(EgoCruiseSetting);
            break;
          }
          case 42: {
            if (mode_ == null) {
              Mode = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SyncMode();
            }
            input.ReadMessage(Mode);
            break;
          }
          case 58: {
            if (simulationSettings_ == null) {
              SimulationSettings = new global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationSettings();
            }
            input.ReadMessage(SimulationSettings);
            break;
          }
          case 66: {
            ClientKey = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// 시뮬레이션 할 맵과 Ego 차량 선택
  /// </summary>
  public sealed partial class MapAndVehicle : pb::IMessage<MapAndVehicle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MapAndVehicle> _parser = new pb::MessageParser<MapAndVehicle>(() => new MapAndVehicle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MapAndVehicle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.StartParamReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MapAndVehicle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MapAndVehicle(MapAndVehicle other) : this() {
      mapName_ = other.mapName_;
      egoVehicleModel_ = other.egoVehicleModel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MapAndVehicle Clone() {
      return new MapAndVehicle(this);
    }

    /// <summary>Field number for the "map_name" field.</summary>
    public const int MapNameFieldNumber = 1;
    private string mapName_ = "";
    /// <summary>
    /// 맵 이름
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MapName {
      get { return mapName_; }
      set {
        mapName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ego_vehicle_model" field.</summary>
    public const int EgoVehicleModelFieldNumber = 2;
    private string egoVehicleModel_ = "";
    /// <summary>
    /// Ego 차량의 모델 명
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EgoVehicleModel {
      get { return egoVehicleModel_; }
      set {
        egoVehicleModel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MapAndVehicle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MapAndVehicle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapName != other.MapName) return false;
      if (EgoVehicleModel != other.EgoVehicleModel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MapName.Length != 0) hash ^= MapName.GetHashCode();
      if (EgoVehicleModel.Length != 0) hash ^= EgoVehicleModel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MapName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MapName);
      }
      if (EgoVehicleModel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EgoVehicleModel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MapName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MapName);
      }
      if (EgoVehicleModel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EgoVehicleModel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MapName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MapName);
      }
      if (EgoVehicleModel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EgoVehicleModel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MapAndVehicle other) {
      if (other == null) {
        return;
      }
      if (other.MapName.Length != 0) {
        MapName = other.MapName;
      }
      if (other.EgoVehicleModel.Length != 0) {
        EgoVehicleModel = other.EgoVehicleModel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MapName = input.ReadString();
            break;
          }
          case 18: {
            EgoVehicleModel = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MapName = input.ReadString();
            break;
          }
          case 18: {
            EgoVehicleModel = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// 시뮬레이션 설정
  /// </summary>
  public sealed partial class SimulationSettings : pb::IMessage<SimulationSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SimulationSettings> _parser = new pb::MessageParser<SimulationSettings>(() => new SimulationSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SimulationSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.StartParamReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimulationSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimulationSettings(SimulationSettings other) : this() {
      moraiScenarioFilename_ = other.moraiScenarioFilename_;
      sensorSettingFilename_ = other.sensorSettingFilename_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimulationSettings Clone() {
      return new SimulationSettings(this);
    }

    /// <summary>Field number for the "morai_scenario_filename" field.</summary>
    public const int MoraiScenarioFilenameFieldNumber = 1;
    private string moraiScenarioFilename_ = "";
    /// <summary>
    /// MORAI SIM 의 시나리오 파일 이름
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MoraiScenarioFilename {
      get { return moraiScenarioFilename_; }
      set {
        moraiScenarioFilename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sensor_setting_filename" field.</summary>
    public const int SensorSettingFilenameFieldNumber = 2;
    private string sensorSettingFilename_ = "";
    /// <summary>
    /// 센서 설정 파일 이름
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SensorSettingFilename {
      get { return sensorSettingFilename_; }
      set {
        sensorSettingFilename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SimulationSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SimulationSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MoraiScenarioFilename != other.MoraiScenarioFilename) return false;
      if (SensorSettingFilename != other.SensorSettingFilename) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MoraiScenarioFilename.Length != 0) hash ^= MoraiScenarioFilename.GetHashCode();
      if (SensorSettingFilename.Length != 0) hash ^= SensorSettingFilename.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MoraiScenarioFilename.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MoraiScenarioFilename);
      }
      if (SensorSettingFilename.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SensorSettingFilename);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MoraiScenarioFilename.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MoraiScenarioFilename);
      }
      if (SensorSettingFilename.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SensorSettingFilename);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MoraiScenarioFilename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MoraiScenarioFilename);
      }
      if (SensorSettingFilename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SensorSettingFilename);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SimulationSettings other) {
      if (other == null) {
        return;
      }
      if (other.MoraiScenarioFilename.Length != 0) {
        MoraiScenarioFilename = other.MoraiScenarioFilename;
      }
      if (other.SensorSettingFilename.Length != 0) {
        SensorSettingFilename = other.SensorSettingFilename;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MoraiScenarioFilename = input.ReadString();
            break;
          }
          case 18: {
            SensorSettingFilename = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MoraiScenarioFilename = input.ReadString();
            break;
          }
          case 18: {
            SensorSettingFilename = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SimulationModeParam : pb::IMessage<SimulationModeParam>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SimulationModeParam> _parser = new pb::MessageParser<SimulationModeParam>(() => new SimulationModeParam());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SimulationModeParam> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.StartParamReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimulationModeParam() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimulationModeParam(SimulationModeParam other) : this() {
      mode_ = other.mode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimulationModeParam Clone() {
      return new SimulationModeParam(this);
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 1;
    private global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType mode_ = global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType.Normal;
    /// <summary>
    /// 1. Normal, 2. Scenario runner, 3. Datagen, 4.....
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType Mode {
      get { return mode_; }
      set {
        mode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SimulationModeParam);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SimulationModeParam other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mode != other.Mode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Mode != global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType.Normal) hash ^= Mode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Mode != global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType.Normal) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Mode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Mode != global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType.Normal) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Mode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Mode != global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType.Normal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Mode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SimulationModeParam other) {
      if (other == null) {
        return;
      }
      if (other.Mode != global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType.Normal) {
        Mode = other.Mode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Mode = (global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Mode = (global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.SimulationModeType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SendMessageParam : pb::IMessage<SendMessageParam>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SendMessageParam> _parser = new pb::MessageParser<SendMessageParam>(() => new SendMessageParam());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SendMessageParam> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreLib.Grpc.Protobuf.MoraiSimAPI.Simulation.StartParamReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendMessageParam() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendMessageParam(SendMessageParam other) : this() {
      type_ = other.type_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendMessageParam Clone() {
      return new SendMessageParam(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private uint type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SendMessageParam);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SendMessageParam other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SendMessageParam other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
